# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

project: abstention-bench

gpus: 1

hydra:
  launcher:
    gpus_per_node: ${gpus}
    tasks_per_node: ${gpus}
    cpus_per_task: 8
    mem_gb: 480
    nodes: 1
    timeout_min: 400
    max_num_timeout: 5
    partition: null
    comment: ${project}
