# @package _global_

model_name: Llama3_1_405B_Instruct_FP8

module:
  _target_: recipe.models.${model_name}
  local_model_path: /large_experiments/robust_vlm/abstention-bench/huggingface/Llama-3.1-405B-Instruct-FP8
  temperature: 0.8
  top_p: 0.95
  # 99.9% of responses are below 4k tokens; 
  # this avoids infinite generation loops in model responses
  max_tokens: 4000
  convert_prompt_to_chat: True
  tensor_parallel_size: 8  # Recommended between 4 and max number of available GPUs
  max_model_len: 32768   # Context window
