# @package _global_

model_name: Qwen2_5_32B_Instruct

module:
  _target_: recipe.models.${model_name}
  local_model_path: "/large_experiments/robust_vlm/abstention-bench/huggingface/Qwen2.5-32B-Instruct"
  temperature: 0.8
  top_p: 0.95
  # 99.9% of responses are below 4k tokens;
  # this avoids infinite generation loops in model responses
  max_tokens: 4000
  convert_prompt_to_chat: True
  tensor_parallel_size: 8 # Recommended between 4 and max number of available GPUs
  max_model_len: 3768 # Context window
  enforce_eager: True
