# @package _global_

dataset_name: MoralChoiceDataset

datamodule:
  _target_: abstentionbench.recipe.abstention_datasets.moralchoice.${dataset_name}
  template_type: "ab"
  system_instruction: True
  max_num_samples: null